name: Build and Release PHP Package

on:
  push:
    tags:
      - 'v*' # 当推送带 v 前缀的标签时触发，例如 v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Next.js project and export static HTML
        run: |
          npm run build
          npm run export
        
      - name: Create PHP wrapper structure
        run: |
          mkdir -p php-build
          # 复制 export 生成的静态文件
          cp -r out/. php-build/
          
          # 创建 PHP 入口文件
          cat > php-build/index.php << 'EOF'
          <?php
          // PHP 项目配置信息
          $config = [
            'api_base' => '/api',
            'version' => '<?php echo getenv("VERSION") ?: "1.0.0"; ?>',
          ];
          
          // 加载静态导出后的 HTML
          $nextJsPath = "./index.html";
          
          if (file_exists($nextJsPath)) {
            $content = file_get_contents($nextJsPath);
            // 在这里可以对 Next.js 输出内容进行修改
            echo $content;
          } else {
            echo "应用加载失败，请检查构建是否正确完成。";
          }
          ?>
          EOF
          
          # 创建简单的 PHP API 代理，允许 Next.js 应用访问 API
          mkdir -p php-build/api
          cat > php-build/api/index.php << 'EOF'
          <?php
          header('Content-Type: application/json');
          
          // 根据请求路径进行路由分发
          $path = $_SERVER['PATH_INFO'] ?? '';
          
          if ($path == '/update-steps') {
            include_once('update-steps.php');
          } else {
            http_response_code(404);
            echo json_encode(['error' => 'API endpoint not found']);
          }
          ?>
          EOF
          
          # 将 API 文件转换为 PHP 文件
          cp pages/api/ZeppLifeSteps.js php-build/api/ZeppLifeSteps.php
          cp pages/api/update-steps.js php-build/api/update-steps.php
          
          # 创建一个简单的 README
          cat > php-build/README.md << 'EOF'
          # Zepp Life 步数修改 PHP 版
          
          这是通过 GitHub Actions 自动构建的 PHP 版本，方便部署在支持 PHP 的服务器上。
          
          ## 使用方法
          
          1. 将整个文件夹上传到支持 PHP 的服务器
          2. 访问 index.php 文件
          3. 按照界面提示操作修改步数
          
          ## 技术说明
          
          该项目是基于 Next.js 构建的应用转换为 PHP 部署版本。
          EOF
          
      - name: Convert JS to PHP format
        run: |
          # 为了支持 PHP 环境运行，需要对 JS 文件进行调整
          # 此处用简单的替换来演示，实际应用中可能需要更复杂的转换逻辑
          
          # 修改 API 文件
          sed -i 's/export default/function handleRequest/' php-build/api/update-steps.php
          echo "module.exports = handleRequest;" >> php-build/api/update-steps.php
          
          # 添加必要的 PHP 头部
          sed -i '1i<?php' php-build/api/update-steps.php
          echo "?>" >> php-build/api/update-steps.php
          
          sed -i '1i<?php' php-build/api/ZeppLifeSteps.php
          echo "?>" >> php-build/api/ZeppLifeSteps.php
          
      - name: Package the project
        run: |
          cd php-build
          zip -r ../zepp-life-steps-php.zip .
          cd ..
          
      - name: Create and Upload GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: zepp-life-steps-php.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 